# Generated by Django 5.2.12 on 2026-04-04 03:31

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=16, unique=True, verbose_name='银行号')),
                ('bank_name', models.CharField(max_length=128, verbose_name='银行名称')),
            ],
            options={
                'verbose_name': '银行',
                'verbose_name_plural': '银行',
                'ordering': ['bank_code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('role', models.CharField(choices=[('normal', '普通员工'), ('quality_inspector', '银行审核员')], default='normal', max_length=32, verbose_name='角色')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='apply.bank', verbose_name='所属银行')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=64, verbose_name='申请人姓名')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申请额度')),
                ('status', models.CharField(choices=[('pending_first', '待初审'), ('first_pass', '初审通过'), ('first_reject', '初审拒绝'), ('pending_second', '待复审'), ('second_pass', '复审通过'), ('second_reject', '复审拒绝'), ('credit_ing', '信审中'), ('issued', '已发卡'), ('rejected', '信审拒绝'), ('returned', '退回补充')], default='pending_first', max_length=32, verbose_name='状态')),
                ('card_number', models.CharField(blank=True, default='', max_length=32, verbose_name='虚拟卡号')),
                ('return_reason', models.TextField(blank=True, default='', verbose_name='退回原因')),
                ('supplementary_note', models.TextField(blank=True, default='', verbose_name='补充说明')),
                ('init_audit_time', models.DateTimeField(blank=True, null=True, verbose_name='初审通过时间')),
                ('credit_time', models.DateTimeField(blank=True, null=True, verbose_name='信审时间')),
                ('credit_remark', models.TextField(blank=True, default='', verbose_name='信审备注')),
                ('issue_data', models.JSONField(blank=True, null=True, verbose_name='发卡快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='关联员工')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='apply.bank', verbose_name='所属银行')),
            ],
            options={
                'verbose_name': '信贷申请',
                'verbose_name_plural': '信贷申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=64, verbose_name='结果')),
                ('comment', models.TextField(blank=True, default='', verbose_name='意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='apply.application', verbose_name='申请单')),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('product_type', models.CharField(max_length=64, verbose_name='产品类型')),
                ('credit_limit_min', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='最低额度')),
                ('credit_limit_max', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='最高额度')),
                ('annual_fee_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='年费率')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_products', to='apply.bank', verbose_name='所属银行')),
            ],
            options={
                'verbose_name': '卡产品',
                'verbose_name_plural': '卡产品',
                'ordering': ['bank', 'product_name'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='card_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='apply.cardproduct', verbose_name='申请卡种'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('bank', 'username'), name='uniq_bank_username'),
        ),
    ]
