# Generated by Django 5.2.12 on 2026-04-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='second_reject_reason',
            field=models.TextField(blank=True, default='', verbose_name='复审拒绝原因'),
        ),
    ]
