# Generated by Django 5.2.12 on 2026-04-05 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_application_second_reject_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index', models.PositiveSmallIntegerField(choices=[(0, '基本信息'), (1, '详细信息'), (2, '影像采集'), (3, '银行专用栏')], help_text='0=基本信息，1=详细信息，2=影像采集，3=银行专用栏', unique=True, verbose_name='页面序号')),
                ('page_title', models.CharField(help_text='显示在进件表单标签页上的标题', max_length=64, verbose_name='页面标题')),
                ('description', models.TextField(blank=True, default='', help_text='该页面的简短说明，供内部参考', verbose_name='页面说明')),
                ('is_active', models.BooleanField(default=True, help_text='关闭后该页将在进件表单中隐藏', verbose_name='启用')),
            ],
            options={
                'verbose_name': '总表单页',
                'verbose_name_plural': '总表单页',
                'ordering': ['page_index'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(help_text='显示在表单中的字段名称，例如：中文姓名', max_length=64, verbose_name='字段标签')),
                ('field_key', models.CharField(help_text='字段的唯一标识键名，例如：applicant_name 或 AP_MARRIAGE', max_length=64, verbose_name='字段名（数据库存储键）')),
                ('field_type', models.CharField(choices=[('text', '单行文本'), ('textarea', '多行文本'), ('select', '下拉框'), ('radio', '单选框'), ('checkbox', '复选框'), ('date', '日期'), ('number', '数字'), ('file', '文件上传'), ('image', '图片上传'), ('phone', '手机号'), ('id_card', '身份证号')], default='text', max_length=32, verbose_name='字段类型')),
                ('is_required', models.BooleanField(default=True, verbose_name='必填')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='同一页面内字段的显示顺序，数字越小越靠前', verbose_name='排序')),
                ('placeholder', models.CharField(blank=True, default='', help_text='输入框内的提示文字', max_length=128, verbose_name='占位提示')),
                ('options', models.TextField(blank=True, default='', help_text='下拉框/单选框的选项，每行一个，格式：值|显示文字', verbose_name='选项内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('page', models.ForeignKey(help_text='该字段属于哪一个表单页', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='apply.formpage', verbose_name='所属页面')),
            ],
            options={
                'verbose_name': '子表单字段',
                'verbose_name_plural': '子表单字段',
                'ordering': ['page__page_index', 'sort_order'],
            },
        ),
    ]
