# Generated by Django 5.2.12 on 2026-04-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_add_form_config_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['page__order', 'sort_order'], 'verbose_name': '子表单字段', 'verbose_name_plural': '子表单字段'},
        ),
        migrations.AlterModelOptions(
            name='formpage',
            options={'ordering': ['order'], 'verbose_name': '总表单页', 'verbose_name_plural': '总表单页'},
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='page_index',
        ),
        migrations.AddField(
            model_name='formpage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='数字越小越靠前，可通过拖拽调整顺序', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_key',
            field=models.CharField(help_text='字段的唯一标识键名，例如：applicant_name', max_length=64, verbose_name='字段名（数据库存储键）'),
        ),
    ]
