# Generated by Django 5.2.12 on 2026-04-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_formpage_order_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardproduct',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='注意事项'),
        ),
        migrations.AddField(
            model_name='cardproduct',
            name='product_desc',
            field=models.TextField(blank=True, default='', verbose_name='产品特点'),
        ),
        migrations.AddField(
            model_name='cardproduct',
            name='product_points',
            field=models.TextField(blank=True, default='', verbose_name='产品要点'),
        ),
        migrations.AddField(
            model_name='cardproduct',
            name='required_docs',
            field=models.TextField(blank=True, default='', verbose_name='需要资料'),
        ),
    ]
