# Generated by Django 5.2.12 on 2026-04-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0005_add_card_product_details'),
        ('apply', '0005_application_form_data'),
    ]

    operations = [
    ]
