# Generated by Django 5.2.12 on 2026-04-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_merge_20260405_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='max_length',
            field=models.PositiveSmallIntegerField(blank=True, help_text='控制该字段可输入的最大字符数，不设置则不限制', null=True, verbose_name='最大长度'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='validation_rule',
            field=models.CharField(blank=True, choices=[('', '无校验'), ('name', '姓名校验'), ('id_card', '身份证号校验'), ('phone', '手机号校验'), ('amount_range', '金额区间校验')], default='', help_text='选择自动应用的校验规则，如姓名、身份证、手机号、金额区间等', max_length=32, verbose_name='校验规则'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', '单行文本'), ('textarea', '多行文本'), ('select', '下拉框'), ('radio', '单选框'), ('checkbox', '复选框'), ('date', '日期'), ('number', '数字'), ('file', '文件上传'), ('image', '图片上传'), ('phone', '手机号'), ('id_card', '身份证号'), ('name', '姓名'), ('amount', '申请金额')], default='text', max_length=32, verbose_name='字段类型'),
        ),
    ]
