# Generated by Django 5.2.12 on 2026-04-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0007_add_validation_rule_and_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='max_photos',
            field=models.PositiveSmallIntegerField(blank=True, help_text='图片上传字段的最多张数限制，不设置则不限制（仅图片字段有效）', null=True, verbose_name='最多图片张数'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='min_photos',
            field=models.PositiveSmallIntegerField(blank=True, help_text='图片上传字段的最少张数要求，不设置则不限制（仅图片字段有效）', null=True, verbose_name='最少图片张数'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', '单行文本'), ('textarea', '多行文本'), ('select', '下拉框'), ('radio', '单选框'), ('checkbox', '复选框'), ('date', '日期'), ('number', '数字'), ('file', '文件上传'), ('image', '图片上传'), ('phone', '手机号'), ('id_card', '身份证号'), ('name', '姓名'), ('name_pinyin', '姓名拼音'), ('amount', '申请金额')], default='text', max_length=32, verbose_name='字段类型'),
        ),
    ]
