# Generated by Django 5.2.12 on 2026-04-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0008_add_photo_count_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['-is_featured', 'bank_code'], 'verbose_name': '银行', 'verbose_name_plural': '银行'},
        ),
        migrations.AddField(
            model_name='bank',
            name='brand_color',
            field=models.CharField(default='#3182ce', help_text='十六进制颜色代码，如 #E74C3C', max_length=7, verbose_name='品牌色'),
        ),
        migrations.AddField(
            model_name='bank',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='热门银行'),
        ),
        migrations.AlterField(
            model_name='cardproduct',
            name='product_desc',
            field=models.TextField(blank=True, default='', verbose_name='产品简介'),
        ),
        migrations.AlterField(
            model_name='cardproduct',
            name='product_points',
            field=models.TextField(blank=True, default='', verbose_name='产品特点'),
        ),
        migrations.AlterField(
            model_name='cardproduct',
            name='required_docs',
            field=models.TextField(blank=True, default='', verbose_name='产品要点'),
        ),
    ]
