# Generated by Django 5.2.12 on 2026-04-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0009_add_bank_brand_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visible_menus',
            field=models.JSONField(blank=True, default=list, help_text='为空时显示全部窗口；超级管理员不受此限制。', verbose_name='可见窗口'),
        ),
    ]
