# Generated by Django 5.2.12 on 2026-04-06 02:49

from django.db import migrations, models


MENU_ITEMS = [
    ("nav_home",   "导航",    "首页"),
    ("base_bank",  "基础数据", "银行"),
    ("base_user",  "基础数据", "用户"),
    ("base_card",  "基础数据", "卡产品"),
    ("biz_apply",  "业务流程", "进件申请"),
    ("biz_audit",  "业务流程", "审核记录"),
    ("form_page",  "表单配置", "总表单页"),
    ("form_field", "表单配置", "子表单字段"),
]


def seed_menu_items_and_migrate_data(apps, schema_editor):
    """填充 MenuItem 初始数据，并将已有用户的 visible_menus JSON 迁移到 M2M。"""
    MenuItem = apps.get_model("apply", "MenuItem")
    User = apps.get_model("apply", "User")

    # 1. 插入菜单项
    for key, group, name in MENU_ITEMS:
        MenuItem.objects.update_or_create(key=key, defaults={"group": group, "name": name})

    # 2. 迁移已有 visible_menus（JSONField → ManyToMany）
    key_to_menu_item = {mi.key: mi for mi in MenuItem.objects.all()}
    for user in User.objects.all():
        old_visible = getattr(user, "visible_menus", None) or []
        if old_visible:
            menu_items = [key_to_menu_item[k] for k in old_visible if k in key_to_menu_item]
            if menu_items:
                user.visible_menu_items.add(*menu_items)


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0010_add_user_visible_menus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='菜单标识')),
                ('group', models.CharField(max_length=64, verbose_name='菜单分组')),
                ('name', models.CharField(max_length=128, verbose_name='显示名称')),
            ],
            options={
                'verbose_name': '菜单项',
                'verbose_name_plural': '菜单项',
                'db_table': 'apply_menu_item',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='bank',
            name='brand_color',
            field=models.CharField(choices=[('#3182ce', '蓝色'), ('#2196f3', '亮蓝色'), ('#03a9f4', '浅蓝色'), ('#00bcd4', '青色'), ('#009688', '青绿色'), ('#27ae60', '绿色'), ('#4caf50', '亮绿色'), ('#8bc34a', '浅绿色'), ('#cddc39', '黄绿色'), ('#ffeb3b', '黄色'), ('#ffc107', '琥珀色'), ('#ff9800', '橙色'), ('#ff5722', '深橙色'), ('#e74c3c', '红色'), ('#c0392b', '深红色'), ('#e91e63', '粉红色'), ('#9c27b0', '紫色'), ('#9b59b6', '淡紫色'), ('#673ab7', '深紫色'), ('#3f51b5', '靛蓝色'), ('#607d8b', '蓝灰色'), ('#795548', '棕色'), ('#9e9e9e', '灰色'), ('#000000', '黑色')], default='#3182ce', help_text='选择银行品牌色，将用于卡片与界面展示。', max_length=7, verbose_name='品牌色'),
        ),
        migrations.AddField(
            model_name='user',
            name='visible_menu_items',
            field=models.ManyToManyField(blank=True, related_name='users', to='apply.menuitem', verbose_name='可见窗口'),
        ),
        # 数据迁移：填充 MenuItem + 将 JSONField 转为 M2M
        migrations.RunPython(seed_menu_items_and_migrate_data),
    ]
