# Generated by Django 5.2.12 on 2026-04-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0011_add_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='is_readonly',
            field=models.BooleanField(default=False, help_text='开启后该字段在前端显示为灰色且不可编辑，适用于银行号等系统填充字段', verbose_name='置灰只读'),
        ),
    ]
