# Generated by Django 5.2.12 on 2026-04-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0012_add_formfield_is_readonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='credit_audit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='信审通过时间'),
        ),
        migrations.AddField(
            model_name='application',
            name='issued_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='已发卡时间'),
        ),
        migrations.AddField(
            model_name='application',
            name='second_audit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='复审通过时间'),
        ),
        migrations.AlterField(
            model_name='application',
            name='credit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='信审结束时间'),
        ),
    ]
