# Generated by Django 5.2.12 on 2026-04-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0013_application_credit_audit_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='audit_type',
            field=models.CharField(choices=[('first', '初审'), ('second', '复审'), ('credit', '信审')], default='first', max_length=20, verbose_name='审核类型'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_status',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='操作后状态'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_status',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='操作前状态'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', '单行文本'), ('textarea', '多行文本'), ('select', '下拉框'), ('radio', '单选框'), ('checkbox', '复选框'), ('date', '日期'), ('number', '数字'), ('file', '文件上传'), ('image', '图片上传'), ('phone', '手机号'), ('id_card', '身份证号'), ('name', '姓名'), ('name_pinyin', '姓名拼音'), ('amount', '申请金额'), ('sms_code', '短信验证码')], default='text', max_length=32, verbose_name='字段类型'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='validation_rule',
            field=models.CharField(blank=True, choices=[('', '无校验'), ('name', '姓名校验'), ('id_card', '身份证号校验'), ('phone', '手机号校验'), ('amount_range', '金额区间校验'), ('email', '邮箱校验')], default='', help_text='选择自动应用的校验规则，如姓名、身份证、手机号、金额区间等', max_length=32, verbose_name='校验规则'),
        ),
    ]
