# Generated by Django 5.2.12 on 2026-04-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0014_auditlog_enhance'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('apply', '进件流程'), ('admin', '后台操作'), ('issue', '发卡信息')], db_index=True, default='admin', max_length=20, verbose_name='日志类型')),
                ('level', models.CharField(choices=[('DEBUG', '调试'), ('INFO', '信息'), ('WARNING', '警告'), ('ERROR', '错误')], default='INFO', max_length=20, verbose_name='日志级别')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='操作类型')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='操作人ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=150, verbose_name='操作人姓名')),
                ('target_type', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='目标类型')),
                ('target_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='目标ID')),
                ('before_status', models.CharField(blank=True, default='', max_length=50, verbose_name='操作前状态')),
                ('after_status', models.CharField(blank=True, default='', max_length=50, verbose_name='操作后状态')),
                ('extra_data', models.TextField(blank=True, default='', verbose_name='额外数据(JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'apply_operation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['log_type', 'created_at'], name='apply_opera_log_typ_dab15d_idx'), models.Index(fields=['user_id', 'created_at'], name='apply_opera_user_id_daca98_idx'), models.Index(fields=['target_type', 'target_id'], name='apply_opera_target__167119_idx')],
            },
        ),
    ]
